task_name: "agnews"

model:
  number_classes: 78


SSL:
  enable: False
  number_itr: 100000

keywords_update:
  extract_keywords_per_class: [ 50 ]
  keywords_set_keep_max_num: [ 50 ]
  IDF_n: 4
  overwrite_conflict: True


classifier:
  n_epochs: 100
  batch_size: 20
  stop_itr: [ 500 ]
  lr: 2e-6
  eval_interval: 50



trainer_Graph:
  epoch: [ 4,10 ]
  batch_size: 256


file_path:
  save_dir: "agnews"