data_dir_name: "Yelp_x"

model:
  number_classes: 2


SSL:
  enable: True
  number_itr: 100000

keywords_update:
  extract_keywords_per_class: [ 1000 ]
  keywords_set_keep_max_num: [ 1000 ]
  IDF_n: 4
  overwrite_conflict: True


classifier:
  n_epochs: 100
  batch_size: 20
  stop_itr: [ 500 ]
  lr: 2e-6
  eval_interval: 50
  type: "short"



trainer_Graph:
  epoch: [ 4,10 ]
  batch_size: 256


file_path:
  save_dir: "agnews"